# Generated by Django 6.0 on 2025-12-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do produto', max_length=60, verbose_name='Nome')),
                ('descricao', models.TextField(help_text='Descrição completa do produto', verbose_name='Descrição')),
                ('marca', models.CharField(help_text='Marca do Produto', max_length=60, verbose_name='Marca')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do Produto', max_digits=6, verbose_name='Preço')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produtos',
                'ordering': ['nome'],
            },
        ),
    ]
