# Generated by Django 5.2.8 on 2025-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do usuário', max_length=80, verbose_name='Nome')),
                ('email', models.EmailField(help_text='E-mail do usuário', max_length=254, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(help_text='Senha do usuário', max_length=255, verbose_name='Senha')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
                'ordering': ['nome'],
            },
        ),
    ]
