# Generated by Django 6.0 on 2025-12-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='reset_token',
            field=models.CharField(blank=True, help_text='Token para recuperação de senha', max_length=100, null=True, verbose_name='Token de Recuperação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, help_text='Data e hora de expiração do token de recuperação', null=True, verbose_name='Expiração do Token'),
        ),
    ]
